import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "bn";
type Interpolation = Record<string, string | number>;

const copy = {
  en: {
    freeDelivery: "Free Delivery Inside Dhaka", premiumCollection: "Premium Pakistani Three Piece Collection", codAvailable: "Cash On Delivery Available",
    home: "Home", products: "Products", reviews: "Reviews", about: "About", contact: "Contact", search: "Search...", wishlist: "Wishlist", cart: "Cart with {count} items",
    openNavigation: "Open navigation", closeNavigation: "Close navigation", language: "বাংলা", languageLabel: "Switch language", darkMode: "Dark mode", lightMode: "Light mode", themeLabel: "Toggle color theme",
    premium: "Premium Collection", heroHeading: "Elegant Pakistani Three Piece Collection", heroCopy: "Discover exclusive Pakistani Three Piece with premium cotton fabric, luxury finishing, and modern elegance.", shopNow: "Shop Now", featuredCollection: "Featured Collection", featuredHeading: "Our Best Selling Collection", featuredCopy: "Discover our premium Pakistani Three Piece collection, carefully selected for elegance and comfort.", latestCollection: "Latest Collection", latestHeading: "All Pakistani Three Piece", latestCopy: "Premium quality Pakistani Three Piece for every occasion.", allProducts: "All Products", featured: "Featured",
    loadingCollection: "Loading collection...", loadingProduct: "Loading product...", productUnavailable: "This product could not be found.", collectionUnavailable: "The collection is temporarily unavailable.", backToTop: "Back to top", imageGallery: "Product image gallery", viewImage: "View image {index} of {name}", youMayLike: "You May Like", savedWishlist: "Saved to Wishlist",
    imageUnavailable: "Image unavailable", outOfStock: "Out of stock", addToCart: "Add To Cart", viewDetails: "View Details", removeWishlist: "Remove from wishlist", addWishlist: "Add to wishlist",
    cartTitle: "Shopping Cart", yourCart: "Your Cart", loadingCart: "Loading your cart...", emptyCart: "Your Cart is Empty", cartEmptyCopy: "Add your favorite Pakistani Three Piece.", continueShopping: "Continue Shopping", decreaseQuantity: "Decrease quantity", increaseQuantity: "Increase quantity", remove: "Remove", subtotal: "Subtotal", deliveryAtCheckout: "Delivery charge will be confirmed during checkout.", placeOrder: "Place Order",
    wishlistTitle: "Saved Favorites", yourWishlist: "Your Wishlist", emptyWishlist: "Your Wishlist is Empty", wishlistEmptyCopy: "Save your favorite Pakistani Three Piece for later.",
    secureCheckout: "Secure Checkout", loadingCheckout: "Loading checkout...", emptyCheckout: "Your cart is empty", emptyCheckoutCopy: "Add a product before checkout.", completeOrder: "Complete Your Order", deliveryDetails: "Delivery Details", fullName: "Full Name", phoneNumber: "Phone Number", districtArea: "District / Area", fullAddress: "Full Delivery Address", paymentMethod: "Payment Method", transactionId: "Transaction ID", submittedAmount: "Submitted Amount (৳)", confirmOrder: "Confirm Order", placingOrder: "Placing Order...", orderSummary: "Order Summary", delivery: "Delivery", freeDhaka: "Free inside Dhaka", estimatedTotal: "Estimated total", orderFinalNote: "Final totals and availability are validated by Rabiora before the order is created.", checkoutError: "Unable to place the order. Please try again.", loadingConfirmation: "Loading your order confirmation...", confirmationUnavailable: "Order confirmation unavailable", returnHome: "Return Home", orderReceived: "Order Received", thankYouOrder: "Thank You for Your Order", orderPendingCopy: "Your order has been recorded with status pending. We will confirm it shortly.", deliveryCharge: "Delivery charge", total: "Total", sendWhatsApp: "Send Order on WhatsApp", manualPayment: "manual payment", manualPaymentCopy: "Enter the transaction ID and the amount you submitted. Your payment will be reviewed manually; it is not automatically verified.",
    productDetails: "Product Details", category: "Category", fabric: "Fabric", color: "Color", availability: "Availability", inStock: "In Stock", description: "Description", buyNow: "Buy Now", addToWishlist: "Add To Wishlist", relatedProducts: "Related Products",
    account: "Rabiora Account", myAccount: "My Account", customer: "Rabiora Customer", welcomeBack: "Welcome Back", createYourAccount: "Create Your Account", loginCopy: "Sign in to keep your cart and wishlist across devices.", registerCopy: "Create an account for faster checkout and order history.", name: "Name", bangladeshPhone: "Bangladesh Phone Number", phoneNotProvided: "Not provided", savedWishlistItems: "Saved wishlist items", emailOptional: "Email (optional)", saveProfile: "Save Profile", saving: "Saving...", myOrders: "My Orders", loadingOrderHistory: "Loading order history...", emptyOrderHistory: "Your completed orders will appear here.", logout: "Logout", pending: "pending", confirmed: "confirmed", shipped: "shipped", delivered: "delivered", login: "Login", register: "Create an account", password: "Password", createAccount: "Create Account", pleaseWait: "Please wait...", continueError: "Unable to continue. Please try again.", alreadyMember: "Already have an account?", newToRabiora: "New to Rabiora?",
    whyRabiora: "Why Rabiora?", whyLove: "Why Customers Love Us", premiumFabric: "Premium Fabric", premiumFabricCopy: "High-quality Pakistani cotton fabric with elegant finishing.", fastDelivery: "Fast Delivery", fastDeliveryCopy: "Quick delivery across Bangladesh with Cash on Delivery.", trustedQuality: "Trusted Quality", trustedQualityCopy: "Every dress is carefully selected before delivery.", support: "24/7 Support", supportCopy: "Friendly customer support whenever you need help.", customerReviews: "Customer Reviews", whatCustomersSay: "What Our Customers Say", reviewsEmpty: "Verified customer reviews will be shared here as they become available.", aboutStore: "Premium Pakistani Three Piece Store", aboutCopy: "Rabiora is committed to providing premium quality Pakistani Three Piece collections with elegant designs, comfortable fabrics, and affordable prices. Our mission is to deliver trusted fashion with excellent customer service.", paymentMethods: "Payment Methods", easyPayment: "Easy Payment", getInTouch: "Get In Touch", address: "Address", phone: "Phone", email: "Email", allRightsReserved: "All Rights Reserved.", designedDevelopedBy: "Designed & Developed by",
  },
  bn: {
    freeDelivery: "ঢাকার ভিতরে ফ্রি ডেলিভারি", premiumCollection: "প্রিমিয়াম পাকিস্তানি থ্রি পিস কালেকশন", codAvailable: "ক্যাশ অন ডেলিভারি সুবিধা আছে",
    home: "হোম", products: "পণ্য", reviews: "রিভিউ", about: "আমাদের কথা", contact: "যোগাযোগ", search: "খুঁজুন...", wishlist: "পছন্দের তালিকা", cart: "কার্টে {count}টি পণ্য",
    openNavigation: "নেভিগেশন খুলুন", closeNavigation: "নেভিগেশন বন্ধ করুন", language: "English", languageLabel: "ভাষা পরিবর্তন করুন", darkMode: "ডার্ক মোড", lightMode: "লাইট মোড", themeLabel: "রঙের থিম পরিবর্তন করুন",
    premium: "প্রিমিয়াম কালেকশন", heroHeading: "এলিগ্যান্ট পাকিস্তানি থ্রি পিস কালেকশন", heroCopy: "প্রিমিয়াম কটন ফ্যাব্রিক, লাক্সারি ফিনিশিং ও আধুনিক সৌন্দর্যে সাজানো বিশেষ পাকিস্তানি থ্রি পিস আবিষ্কার করুন।", shopNow: "এখনই দেখুন", featuredCollection: "ফিচারড কালেকশন", featuredHeading: "আমাদের জনপ্রিয় কালেকশন", featuredCopy: "আভিজাত্য ও আরামের জন্য বাছাই করা প্রিমিয়াম পাকিস্তানি থ্রি পিস কালেকশন দেখুন।", latestCollection: "নতুন কালেকশন", latestHeading: "সব পাকিস্তানি থ্রি পিস", latestCopy: "প্রতিটি উপলক্ষের জন্য প্রিমিয়াম মানের পাকিস্তানি থ্রি পিস।", allProducts: "সব পণ্য", featured: "ফিচারড",
    loadingCollection: "কালেকশন লোড হচ্ছে...", loadingProduct: "পণ্য লোড হচ্ছে...", productUnavailable: "পণ্যটি পাওয়া যায়নি।", collectionUnavailable: "কালেকশনটি সাময়িকভাবে পাওয়া যাচ্ছে না।", backToTop: "উপরে যান", imageGallery: "পণ্যের ছবির গ্যালারি", viewImage: "{name}-এর {index} নম্বর ছবি দেখুন", youMayLike: "আপনার পছন্দ হতে পারে", savedWishlist: "পছন্দের তালিকায় সংরক্ষিত",
    imageUnavailable: "ছবি পাওয়া যাচ্ছে না", outOfStock: "স্টক নেই", addToCart: "কার্টে যোগ করুন", viewDetails: "বিস্তারিত দেখুন", removeWishlist: "পছন্দের তালিকা থেকে সরান", addWishlist: "পছন্দের তালিকায় যোগ করুন",
    cartTitle: "শপিং কার্ট", yourCart: "আপনার কার্ট", loadingCart: "আপনার কার্ট লোড হচ্ছে...", emptyCart: "আপনার কার্ট খালি", cartEmptyCopy: "আপনার পছন্দের পাকিস্তানি থ্রি পিস যোগ করুন।", continueShopping: "কেনাকাটা চালিয়ে যান", decreaseQuantity: "পরিমাণ কমান", increaseQuantity: "পরিমাণ বাড়ান", remove: "সরান", subtotal: "সাবটোটাল", deliveryAtCheckout: "চেকআউটের সময় ডেলিভারি চার্জ নিশ্চিত করা হবে।", placeOrder: "অর্ডার করুন",
    wishlistTitle: "সংরক্ষিত পছন্দ", yourWishlist: "আপনার পছন্দের তালিকা", emptyWishlist: "পছন্দের তালিকা খালি", wishlistEmptyCopy: "পরে দেখার জন্য আপনার পছন্দের পাকিস্তানি থ্রি পিস সংরক্ষণ করুন।",
    secureCheckout: "নিরাপদ চেকআউট", loadingCheckout: "চেকআউট লোড হচ্ছে...", emptyCheckout: "আপনার কার্ট খালি", emptyCheckoutCopy: "চেকআউটের আগে একটি পণ্য যোগ করুন।", completeOrder: "অর্ডার সম্পন্ন করুন", deliveryDetails: "ডেলিভারি তথ্য", fullName: "পুরো নাম", phoneNumber: "ফোন নম্বর", districtArea: "জেলা / এলাকা", fullAddress: "পূর্ণ ঠিকানা", paymentMethod: "পেমেন্ট পদ্ধতি", transactionId: "ট্রানজেকশন আইডি", submittedAmount: "জমা দেওয়া পরিমাণ (৳)", confirmOrder: "অর্ডার নিশ্চিত করুন", placingOrder: "অর্ডার করা হচ্ছে...", orderSummary: "অর্ডারের সারাংশ", delivery: "ডেলিভারি", freeDhaka: "ঢাকার ভিতরে ফ্রি", estimatedTotal: "মোট আনুমানিক", orderFinalNote: "অর্ডার তৈরি হওয়ার আগে রাবিওরা চূড়ান্ত মূল্য ও প্রাপ্যতা যাচাই করে।", checkoutError: "অর্ডার করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।", loadingConfirmation: "অর্ডার নিশ্চিতকরণ লোড হচ্ছে...", confirmationUnavailable: "অর্ডার নিশ্চিতকরণ পাওয়া যাচ্ছে না", returnHome: "হোমে ফিরুন", orderReceived: "অর্ডার গ্রহণ করা হয়েছে", thankYouOrder: "অর্ডারের জন্য ধন্যবাদ", orderPendingCopy: "আপনার অর্ডারটি অপেক্ষমাণ অবস্থায় রেকর্ড হয়েছে। আমরা শীঘ্রই নিশ্চিত করব।", deliveryCharge: "ডেলিভারি চার্জ", total: "মোট", sendWhatsApp: "হোয়াটসঅ্যাপে অর্ডার পাঠান", manualPayment: "ম্যানুয়াল পেমেন্ট", manualPaymentCopy: "ট্রানজেকশন আইডি ও জমা দেওয়া পরিমাণ লিখুন। পেমেন্ট ম্যানুয়ালি যাচাই করা হবে; এটি স্বয়ংক্রিয়ভাবে যাচাই হয় না।",
    productDetails: "পণ্যের বিস্তারিত", category: "ক্যাটাগরি", fabric: "ফ্যাব্রিক", color: "রং", availability: "স্টক", inStock: "স্টকে আছে", description: "বিবরণ", buyNow: "এখনই কিনুন", addToWishlist: "পছন্দের তালিকায় যোগ করুন", relatedProducts: "সম্পর্কিত পণ্য",
    account: "রাবিওরা অ্যাকাউন্ট", myAccount: "আমার অ্যাকাউন্ট", customer: "রাবিওরা ক্রেতা", welcomeBack: "আবারও স্বাগতম", createYourAccount: "আপনার অ্যাকাউন্ট তৈরি করুন", loginCopy: "সব ডিভাইসে কার্ট ও পছন্দের তালিকা রাখতে সাইন ইন করুন।", registerCopy: "দ্রুত চেকআউট ও অর্ডার হিস্ট্রির জন্য অ্যাকাউন্ট তৈরি করুন।", name: "নাম", bangladeshPhone: "বাংলাদেশি ফোন নম্বর", phoneNotProvided: "দেওয়া হয়নি", savedWishlistItems: "সংরক্ষিত পছন্দের পণ্য", emailOptional: "ইমেইল (ঐচ্ছিক)", saveProfile: "প্রোফাইল সংরক্ষণ করুন", saving: "সংরক্ষণ হচ্ছে...", myOrders: "আমার অর্ডার", loadingOrderHistory: "অর্ডার হিস্ট্রি লোড হচ্ছে...", emptyOrderHistory: "আপনার সম্পন্ন অর্ডারগুলো এখানে দেখানো হবে।", logout: "লগআউট", pending: "অপেক্ষমাণ", confirmed: "নিশ্চিত", shipped: "পাঠানো হয়েছে", delivered: "ডেলিভারি হয়েছে", login: "লগইন", register: "অ্যাকাউন্ট খুলুন", password: "পাসওয়ার্ড", createAccount: "অ্যাকাউন্ট তৈরি করুন", pleaseWait: "অপেক্ষা করুন...", continueError: "চালিয়ে যাওয়া যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।", alreadyMember: "আগেই অ্যাকাউন্ট আছে?", newToRabiora: "রাবিওরাতে নতুন?",
    whyRabiora: "কেন রাবিওরা?", whyLove: "ক্রেতারা কেন পছন্দ করেন", premiumFabric: "প্রিমিয়াম ফ্যাব্রিক", premiumFabricCopy: "দারুণ ফিনিশিংসহ উচ্চমানের পাকিস্তানি কটন ফ্যাব্রিক।", fastDelivery: "দ্রুত ডেলিভারি", fastDeliveryCopy: "ক্যাশ অন ডেলিভারিসহ সারা বাংলাদেশে দ্রুত ডেলিভারি।", trustedQuality: "বিশ্বস্ত মান", trustedQualityCopy: "ডেলিভারির আগে প্রতিটি ড্রেস যত্নসহকারে বাছাই করা হয়।", support: "২৪/৭ সহায়তা", supportCopy: "যেকোনো সময় আপনার জন্য বন্ধুসুলভ সহায়তা।", customerReviews: "ক্রেতাদের মতামত", whatCustomersSay: "ক্রেতারা কী বলেন", reviewsEmpty: "যাচাইকৃত ক্রেতা মতামত পাওয়া গেলে এখানে দেখানো হবে।", aboutStore: "প্রিমিয়াম পাকিস্তানি থ্রি পিস স্টোর", aboutCopy: "এলিগ্যান্ট ডিজাইন, আরামদায়ক ফ্যাব্রিক ও সাশ্রয়ী দামে প্রিমিয়াম পাকিস্তানি থ্রি পিস দিতে রাবিওরা প্রতিশ্রুতিবদ্ধ। আমাদের লক্ষ্য বিশ্বস্ত সেবা ও চমৎকার ফ্যাশন অভিজ্ঞতা নিশ্চিত করা।", paymentMethods: "পেমেন্ট পদ্ধতি", easyPayment: "সহজ পেমেন্ট", getInTouch: "যোগাযোগ করুন", address: "ঠিকানা", phone: "ফোন", email: "ইমেইল", allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।", designedDevelopedBy: "ডিজাইন ও ডেভেলপমেন্ট",
  },
} as const;

type CopyKey = keyof typeof copy.en;
type LanguageContextValue = { language: Language; toggleLanguage: () => void; t: (key: CopyKey, values?: Interpolation) => string };
const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem("rabiora-language") === "bn" ? "bn" : "en"));
  useEffect(() => { document.documentElement.lang = language === "bn" ? "bn" : "en"; localStorage.setItem("rabiora-language", language); }, [language]);
  const value = useMemo<LanguageContextValue>(() => ({
    language,
    toggleLanguage: () => setLanguage((current) => current === "en" ? "bn" : "en"),
    t: (key, values = {}) => {
      const template = copy[language][key] as string;
      return Object.entries(values).reduce<string>((text, [name, value]) => text.replace(`{${name}}`, String(value)), template);
    },
  }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
